name: Quality

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pint:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup PHP
        uses: ./.github/actions/setup
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: 🔮 Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: Install Node Dependencies & Build Assets
        run: npm install && npm run build
      - name: 🕵️‍♂️ Run Laravel Pint
        run: composer test:lint

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup PHP
        uses: ./.github/actions/setup
      - name: 🔮 Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: 🕵️‍♂️ Run PHPStan
        run: composer test:types

  type-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup PHP
        uses: ./.github/actions/setup
        env:
          COMPOSER_AUTH_TOKEN: ${{ secrets.COMPOSER_AUTH_TOKEN }}
      - name: 🔮 Install Composer Dependencies
        run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
      - name: 🕵️‍♂️ Run PHPStan
        run: composer test:type-coverage

  composer:
    runs-on: ubuntu-22.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup
        uses: ./.github/actions/setup
      - name: 🕵️‍♂️ Run Composer Validate
        run: composer validate
      - name: 🕵️‍♂️ Run Composer Audit
        run: composer audit
